## Welcome

These are the materials for workshops on text analysis by [Julia Silge](https://juliasilge.com/). Text data is increasingly important in many domains, and tidy data principles and tidy tools can make text mining easier and more effective. In this workshop, learn how to manipulate, summarize, and visualize the characteristics of text using these methods and R packages from the tidy tool ecosystem. These tools are highly effective for many analytical questions and allow analysts to integrate natural language processing into effective workflows already in wide use. Explore how to implement approaches such as sentiment analysis of texts, measuring tf-idf, network analysis of words, and building both supervised and unsupervised text models.

## Is this workshop for me?

This course will be appropriate for you if you answer yes to these questions:

- Have you ever encountered text data and suspected there was useful insight latent within it but felt frustrated about how to find that insight?
- Are you familiar with dplyr and ggplot2, and ready to learn how unstructured text data can be analyzed within the [tidyverse](https://www.tidyverse.org/) ecosystem?
- Do you need a flexible framework for handling text data that allows you to engage in tasks from exploratory data analysis to supervised predictive modeling?


## Learning objectives

At the end of this workshop, participants will understand how to: 

- Perform exploratory data analyses of text datasets, including summarization and data visualization
- Understand and implement both sentiment analysis and tf-idf
- Use unsupervised models to gain insight into text data
- Build supervised classification models for text using tidy data principles


## Preparation

Please tune into the workshop with a computer that has the following installed (all available for free):

- A recent version of R, available at <https://cran.r-project.org/>
- A recent version of RStudio Desktop (RStudio Desktop Open Source License), available at <https://posit.co/download/rstudio-desktop/>
- The following R packages, which you can install by connecting to the internet, opening RStudio, and running at the command line:

```{r}
#| eval: false
install.packages(c("tidyverse", "tidytext", 
                   "gutenbergr", "widyr",
                   "stopwords", "stm",
                   "tidygraph", "ggraph",
                   "tidymodels", "glmnet", 
                   "vip", "textrecipes"))

```

## Slides

- 00: [Intro](slides/00-intro.html)
- 01: [Text as tidy data](slides/01-tidytext.html)
- 02: [More advanced EDA](slides/02-more-eda.html)
- 03: [Topic modeling](slides/03-topic-models.html)
- 04: [Supervised text models](slides/04-sml-text.html)

## Code

Quarto files for working along [are available on GitHub](https://github.com/juliasilge/tidytext-tutorial/tree/master/code).

## Past workshops

- [16 October 2017 for Portland R-Ladies and Portland R User Group](https://www.meetup.com/R-Ladies-PDX/events/243376514/)
- [18 April 2018 for R-Ladies RTP](https://www.meetup.com/R-Ladies-RTP/events/248456720/)
- [22 May 2018 for III International Seminar on Statistics with R](https://ser2018.weebly.com/programmee.html)
- [29 May 2019 for ASA Symposium on Data Science and Statistics](https://github.com/juliasilge/sdss2019)
- [27-28 January 2020 at rstudio::conf()](https://education.rstudio.com/blog/2020/02/conf20-tidytext/)
- [10 February 2021 for National Institute of Statistical Sciences](https://www.niss.org/events/essential-data-science-business-unstructured-data-analysis-text-mining-tidy-data-principles)
- [10 February 2021 for National Institute of Statistical Sciences](https://www.niss.org/events/essential-data-science-business-unstructured-data-analysis-text-mining-tidy-data-principles)
- 9-11 January 2022 for Faculty of Psychology, University of Basel

## Instructor bio

Julia Silge is a data scientist and software engineer at [Posit PBC](https://posit.co/) (formerly RStudio) where she works on open source modeling and MLOps tools. She is an author, an international keynote speaker, and a real-world practitioner focusing on data analysis and machine learning. Julia loves text analysis, making beautiful charts, and communicating about technical topics with diverse audiences.
